### ISSUE TITLE
SyncedCron throwing exception

### ISSUE THREAD

**Issue by jykae** [Digipalvelutehdas/dipor-dashboard#247]
Happens with the latest from "develop" branch. First run succeeds, second throws exception:

```
SyncedCron: Exception "Get Github issue data for service" TypeError: Cannot call method 'toISOString' of undefined
    at /Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/app/app.js:758:115
    at SynchronousCursor.forEach (/Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/packages/mongo.js:998:18)
    at Cursor.(anonymous function) [as forEach] (/Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/packages/mongo.js:850:44)
    at Object.job (/Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/app/app.js:756:22)
    at packages/percolate_synced-cron.js:242:26
    at scheduleTimeout (packages/percolate_synced-cron.js:290:7)
    at packages/percolate_synced-cron.js:338:42
    at [object Object]._.extend.withValue (packages/meteor.js:1100:17)
    at packages/meteor.js:445:45
    at runWithEnvironment (packages/meteor.js:1154:24)
```

**Comment by brylie** [comment]
It looks like the `lastJobEndTime` may not be defined when the cron runs a second time. Check the `cronHistory` findOne call.

Also, make sure the `lastJobEndTime` is specific to the current job, as there will likely be other cron jobs running. I.e. we are not going to add everything to a single cron task.

**Comment by jykae** [comment]
@brylie Alrightey, not getting that anymore.. Closing. Sweet and fast fixing, cool!
