### ISSUE TITLE
Deploy Dipor release based on sprint 5

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#305]
* [x] Once sprint 5 release has been made, run deployment script / command.
* [x] Announce the deployment 
  * [x] in Dipor channel in Slack
  * [x] as a comment to task #293, so that deployment testing can start

**Comment by jykae** [comment]
Mupx is really unstable with Meteor versions greater than 1.3. I am crashing here for MongoDB driver issues, deployment verification etc... 

Arunoda Mupx backlog is full of issues like this. I am trying to downgrade and get this at least running.

**Comment by jykae** [comment]
```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

[dashboard.digipalvelutehdas.fi] npm WARN deprecated This version of npm lacks support for important features,
[dashboard.digipalvelutehdas.fi] npm WARN deprecated such as scoped packages, offered by the primary npm
[dashboard.digipalvelutehdas.fi] npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
[dashboard.digipalvelutehdas.fi] npm WARN deprecated latest stable version. To upgrade to npm@2, run:
[dashboard.digipalvelutehdas.fi] npm WARN deprecated
[dashboard.digipalvelutehdas.fi] npm WARN deprecated   npm -g install npm@latest-2
[dashboard.digipalvelutehdas.fi] npm WARN deprecated
[dashboard.digipalvelutehdas.fi] npm WARN deprecated To upgrade to the latest stable version, run:
[dashboard.digipalvelutehdas.fi] npm WARN deprecated
[dashboard.digipalvelutehdas.fi] npm WARN deprecated   npm -g install npm@latest
[dashboard.digipalvelutehdas.fi] npm WARN deprecated
[dashboard.digipalvelutehdas.fi] npm WARN deprecated (Depending on how Node.js was installed on your system, you
[dashboard.digipalvelutehdas.fi] npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
[dashboard.digipalvelutehdas.fi] npm WARN deprecated on Windows, run them from an Administrator prompt.)
[dashboard.digipalvelutehdas.fi] npm WARN deprecated
[dashboard.digipalvelutehdas.fi] npm WARN deprecated If you're running the version of npm bundled with
[dashboard.digipalvelutehdas.fi] npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
[dashboard.digipalvelutehdas.fi] npm WARN deprecated will be bundled with a version of npm@2, which has some small
[dashboard.digipalvelutehdas.fi] npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
[dashboard.digipalvelutehdas.fi] npm WARN deprecated semver behavior.
[dashboard.digipalvelutehdas.fi] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[dashboard.digipalvelutehdas.fi] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[dashboard.digipalvelutehdas.fi] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[dashboard.digipalvelutehdas.fi] => Starting meteor app on port:80
[dashboard.digipalvelutehdas.fi]
[dashboard.digipalvelutehdas.fi] /bundle/bundle/programs/server/node_modules/fibers/future.js:300
[dashboard.digipalvelutehdas.fi] 						throw(ex);
[dashboard.digipalvelutehdas.fi] 						      ^
[dashboard.digipalvelutehdas.fi] MongoError: driver is incompatible with this server version
[dashboard.digipalvelutehdas.fi]     at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:420:15)
[dashboard.digipalvelutehdas.fi]     at MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:790:10)
[dashboard.digipalvelutehdas.fi]     at [object Object].Mongo.Collection._ensureIndex (packages/mongo/collection.js:664:20)
[dashboard.digipalvelutehdas.fi]     at meteorInstall.integrations.github.issues.collection.collection.js (integrations/github/issues/collection/collection.js:5:16)
[dashboard.digipalvelutehdas.fi]     at fileEvaluate (packages/modules-runtime.js:158:9)
[dashboard.digipalvelutehdas.fi]     at require (packages/modules-runtime.js:92:16)
[dashboard.digipalvelutehdas.fi]     at /bundle/bundle/programs/server/app/app.js:3056:1
[dashboard.digipalvelutehdas.fi]     at /bundle/bundle/programs/server/boot.js:283:10
[dashboard.digipalvelutehdas.fi]     at Array.forEach (native)
[dashboard.digipalvelutehdas.fi]     at Function._.each._.forEach (/bundle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
[dashboard.digipalvelutehdas.fi]     - - - - -
[dashboard.digipalvelutehdas.fi]     at Object.toError (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at __executeInsertCommand (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1926:27)
    at Db._executeInsertCommand (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:2028:5)
    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1348:12
    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1442:20
    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1196:16
    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at [object Object].MongoReply.parseBody (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
```

**Comment by jykae** [comment]
It's crashing on startup to this all the time:

```
[dashboard.digipalvelutehdas.fi] => Starting meteor app on port:80
[dashboard.digipalvelutehdas.fi]
[dashboard.digipalvelutehdas.fi] /bundle/bundle/programs/server/node_modules/fibers/future.js:300
[dashboard.digipalvelutehdas.fi] 						throw(ex);
[dashboard.digipalvelutehdas.fi] 						      ^
[dashboard.digipalvelutehdas.fi] MongoError: driver is incompatible with this server version
[dashboard.digipalvelutehdas.fi]     at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:420:15)
[dashboard.digipalvelutehdas.fi]     at MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:790:10)
[dashboard.digipalvelutehdas.fi]     at [object Object].Mongo.Collection._ensureIndex (packages/mongo/collection.js:664:20)
[dashboard.digipalvelutehdas.fi]     at meteorInstall.integrations.github.issues.collection.collection.js (integrations/github/issues/collection/collection.js:5:16)
[dashboard.digipalvelutehdas.fi]     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
[dashboard.digipalvelutehdas.fi]     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
[dashboard.digipalvelutehdas.fi]     at /bundle/bundle/programs/server/app/app.js:3056:1
[dashboard.digipalvelutehdas.fi]     at /bundle/bundle/programs/server/boot.js:283:10
[dashboard.digipalvelutehdas.fi]     at Array.forEach (native)
[dashboard.digipalvelutehdas.fi]     at Function._.each._.forEach (/bundle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
[dashboard.digipalvelutehdas.fi]     - - - - -
[dashboard.digipalvelutehdas.fi]     at Object.toError (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
[dashboard.digipalvelutehdas.fi]     at __executeInsertCommand (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1926:27)
[dashboard.digipalvelutehdas.fi]     at Db._executeInsertCommand (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:2028:5)
[dashboard.digipalvelutehdas.fi]     at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1348:12
    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1442:20
    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1196:16
    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at [object Object].MongoReply.parseBody (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
```

**Comment by jykae** [comment]
I suspect that there's issue in our code with ensureIndex. I noticed this line in error trace:
```
[dashboard.digipalvelutehdas.fi]     at meteorInstall.integrations.github.issues.collection.collection.js (integrations/github/issues/collection/collection.js:5:16)
```

**Comment by jykae** [comment]
Development Meteor uses 2.6.7 
Production mupx has installed version 3.2.6 of MongoDB

**Comment by jykae** [comment]
Commented out "ensureIndex" functions, causing error, and v0.5.0 is now up and running.
